In [4]:
import numpy as np
import pandas as pd

In [5]:
s= pd.Series([3,2,0,1])
print (s[0])

3

In [76]:
print(s[4]) # out of range error

KeyError: 4

In [7]:
data = {
    'apple': [3,2,0,1],
    'oranges': [0,3,7,2]
}
df= pd.DataFrame(data)
print(df)

   apple  oranges
0      3        0
1      2        3
2      0        7
3      1        2

In [8]:
df=pd.DataFrame(data, index=['June','Robert','Lily','David'])

In [9]:
print(df)

        apple  oranges
June        3        0
Robert      2        3
Lily        0        7
David       1        2

What is the difference between the dataframe in the slide with the output 
of this program?

Ans: The row identifiers have changed from the numbers to the values of the list we've defined

In [10]:
df.head(10)

        apple  oranges
June        3        0
Robert      2        3
Lily        0        7
David       1        2

In [11]:
df.tail(30)

        apple  oranges
June        3        0
Robert      2        3
Lily        0        7
David       1        2

In [12]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [13]:
import os

In [14]:
os.getcwd()

'/workspace/python-ai-course/notebooks'

In [15]:
df1=pd.read_csv("../resources/employees.csv")

In [16]:
df1.head(10)

,employee_id,name,department,city,salary,years_experience,performance_score,hire_date
0,1001,David Wanjiru,HR,Nakuru,132468.0,0,NaN,2015-01-01
1,1002,Paul Wambui,Sales,Nairobi,122705.0,19,4.4,2015-01-19
2,1003,Ann Muthoni,HR,Mombasa,103477.0,16,3.1,2015-02-06
3,1004,David Omondi,Marketing,Mombasa,44388.0,11,1.7,2015-02-25
4,1005,George Achieng,HR,Nakuru,35569.0,14,2.2,2015-03-15
5,1006,Daniel Wambui,Engineering,Nairobi,99836.0,0,2.2,2015-04-02
6,1007,Grace Kariuki,Engineering,Eldoret,134573.0,13,2.6,2015-04-21
7,1008,Peter Njoroge,Marketing,Eldoret,66586.0,5,2.7,2015-05-09
8,1009,Mary Kariuki,Sales,Mombasa,42015.0,4,4.2,2015-05-27
9,1010,Ruth Kiptoo,Engineering,Nairobi,75002.0,10,2.4,2015-06-15

In [17]:
df1.tail(30)

,employee_id,name,department,city,salary,years_experience,performance_score,hire_date
175,1176,Joseph Mwangi,HR,Kisumu,71427.0,2,1.5,2023-10-17
176,1177,Ruth Ochieng,Marketing,Nakuru,109579.0,19,3.9,2023-11-04
177,1178,Esther Odhiambo,Engineering,Mombasa,58746.0,10,1.8,2023-11-23
178,1179,Faith Kamau,Finance,Mombasa,117886.0,5,1.5,2023-12-11
179,1180,Michael Odhiambo,Finance,Mombasa,137141.0,1,2.7,2023-12-29
180,1181,Joseph Kiptoo,Marketing,Mombasa,30117.0,6,4.2,2024-01-17
181,1182,Peter Ochieng,HR,Kisumu,142221.0,17,4.0,2024-02-04
182,1183,James Wanjiru,Sales,Kisumu,114471.0,1,1.2,2024-02-23
183,1184,James Kamau,HR,Mombasa,142613.0,16,2.8,2024-03-12
184,1185,Mercy Njeri,Marketing,Nakuru,43234.0,10,3.1,2024-03-30
185,1186,Joyce Auma,Finance,Nairobi,133864.0,11,3.6,2024-04-18
186,1187,Peter Kariuki,HR,Nairobi,83441.0,18,3.6,2024-05-06
187,1188,Esther Kariuki,Finance,Nakuru,30846.0,6,2.5,2024-05-24
188,1189,Mercy Auma,Sales,Mombasa,40954.0,19,3.2,2024-06-12
189,1190,Mary Auma,Finance,Kisumu,109239.0,5,2.9,2024-06-30
190,1191,Joyce Otieno,Finance,Nairobi,143689.0,0,NaN,2024-07-18
191,1192,Joseph Kariuki,Engineering,Eldoret,76514.0,16,3.1,2024-08-06
192,1193,James Njeri,Engineering,Eldoret,118236.0,10,2.8,2024-08-24
193,1194,Daniel Njoroge,Engineering,Nakuru,127579.0,17,2.6,2024-09-11
194,1195,Lucy Achieng,Finance,Mombasa,36469.0,16,3.3,2024-09-30
195,1196,Joyce Achieng,Marketing,Nairobi,60105.0,6,4.2,2024-10-18
196,1197,Peter Otieno,Finance,Mombasa,72101.0,16,3.2,2024-11-05
197,1198,Samuel Ochieng,Marketing,Nairobi,94323.0,19,3.6,2024-11-24
198,1199,David Njeri,Marketing,Nakuru,121922.0,8,4.0,2024-12-12
199,1200,Grace Muthoni,Engineering,Nakuru,88067.0,16,3.1,2024-12-31
200,1059,Ann Ochieng,Marketing,Eldoret,40478.0,3,4.5,2017-11-30
201,1041,Ann Kiptoo,Finance,Nakuru,53061.0,10,3.3,2017-01-04
202,1035,Joyce Wanjiru,Marketing,Kisumu,87108.0,2,3.2,2016-09-15
203,1103,Nancy Ochieng,Finance,Eldoret,76271.0,9,2.1,2020-02-15
204,1185,Mercy Njeri,Marketing,Nakuru,43234.0,10,3.1,2024-03-30

In [19]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        205 non-null    int64
 1   name               205 non-null    str
 2   department         205 non-null    str
 3   city               205 non-null    str
 4   salary             197 non-null    float64
 5   years_experience   205 non-null    int64
 6   performance_score  190 non-null    float64
 7   hire_date          205 non-null    str
dtypes: float64(2), int64(2), str(4)
memory usage: 12.9 KB

In [21]:
df1.shape

(205, 8)

In [75]:
df1.describe()

       employee_id         salary  years_experience  performance_score
count   205.000000     197.000000        205.000000         190.000000
mean   1100.112195   88551.121827          8.775610           3.151579
std      57.875730   37817.506983          5.698158           1.082019
min    1001.000000   30055.000000          0.000000           1.000000
25%    1050.000000   53275.000000          4.000000           2.400000
50%    1100.000000   88243.000000          8.000000           3.200000
75%    1150.000000  118869.000000         13.000000           4.000000
max    1200.000000  148894.000000         19.000000           5.000000

In [30]:
df1.head(5)

,employee_id,name,department,city,salary,years_experience,performance_score,hire_date
0,1001,David Wanjiru,HR,Nakuru,132468.0,0,NaN,2015-01-01
1,1002,Paul Wambui,Sales,Nairobi,122705.0,19,4.4,2015-01-19
2,1003,Ann Muthoni,HR,Mombasa,103477.0,16,3.1,2015-02-06
3,1004,David Omondi,Marketing,Mombasa,44388.0,11,1.7,2015-02-25
4,1005,George Achieng,HR,Nakuru,35569.0,14,2.2,2015-03-15

In [31]:
df1.iloc[0,2]

'HR'

In [32]:
df1.iloc[1,2]

'Sales'

In [42]:
df1.loc[0 ,'employee_id']

np.int64(1001)

In [50]:
df1.loc[df1['salary']>145000]

,employee_id,name,department,city,salary,years_experience,performance_score,hire_date
10,1011,Faith Otieno,Finance,Mombasa,146594.0,3,2.9,2015-07-03
29,1030,Peter Kiptoo,HR,Nakuru,145359.0,16,4.2,2016-06-16
62,1063,Ruth Kariuki,Finance,Nakuru,148831.0,7,3.5,2018-02-11
96,1097,George Omondi,HR,Nairobi,148033.0,5,1.3,2019-10-28
109,1110,John Mwangi,Sales,Nairobi,146664.0,3,4.4,2020-06-23
127,1128,George Wanjiru,Engineering,Eldoret,148894.0,10,NaN,2021-05-19
151,1152,Ann Wanjiru,Sales,Eldoret,146148.0,7,4.2,2022-08-03
154,1155,Mercy Kiptoo,Sales,Nairobi,146421.0,8,3.8,2022-09-27
161,1162,Ann Achieng,HR,Kisumu,148205.0,13,NaN,2023-02-02
169,1170,Mary Odhiambo,Finance,Nairobi,145751.0,14,1.2,2023-06-29

In [52]:
df1.iloc[0]

employee_id                   1001
name                 David Wanjiru
department                      HR
city                        Nakuru
salary                    132468.0
years_experience                 0
performance_score              NaN
hire_date               2015-01-01
Name: 0, dtype: object

In [53]:
df1.iloc[0:5]

,employee_id,name,department,city,salary,years_experience,performance_score,hire_date
0,1001,David Wanjiru,HR,Nakuru,132468.0,0,NaN,2015-01-01
1,1002,Paul Wambui,Sales,Nairobi,122705.0,19,4.4,2015-01-19
2,1003,Ann Muthoni,HR,Mombasa,103477.0,16,3.1,2015-02-06
3,1004,David Omondi,Marketing,Mombasa,44388.0,11,1.7,2015-02-25
4,1005,George Achieng,HR,Nakuru,35569.0,14,2.2,2015-03-15

In [54]:
df1.iloc[:, 1:3]

               name department
0     David Wanjiru         HR
1       Paul Wambui      Sales
2       Ann Muthoni         HR
3      David Omondi  Marketing
4    George Achieng         HR
..              ...        ...
200     Ann Ochieng  Marketing
201      Ann Kiptoo    Finance
202   Joyce Wanjiru  Marketing
203   Nancy Ochieng    Finance
204     Mercy Njeri  Marketing

[205 rows x 2 columns]

In [56]:
df1.iloc[1:20,1:3]

              name   department
1      Paul Wambui        Sales
2      Ann Muthoni           HR
3     David Omondi    Marketing
4   George Achieng           HR
5    Daniel Wambui  Engineering
6    Grace Kariuki  Engineering
7    Peter Njoroge    Marketing
8     Mary Kariuki        Sales
9      Ruth Kiptoo  Engineering
10    Faith Otieno      Finance
11   James Ochieng  Engineering
12      Ruth Njeri  Engineering
13   Joseph Wambui        Sales
14   Joyce Ochieng           HR
15       Lucy Auma  Engineering
16     Paul Kiptoo    Marketing
17  George Ochieng           HR
18     Nancy Njeri      Finance
19  Peter Odhiambo        Sales

In [59]:
df1.iloc[[0,2,3,4], [1,2,3]]

             name department     city
0   David Wanjiru         HR   Nakuru
2     Ann Muthoni         HR  Mombasa
3    David Omondi  Marketing  Mombasa
4  George Achieng         HR   Nakuru

In [60]:
df1.iloc[1,6]

np.float64(4.4)

In [63]:
df1.loc[1]

employee_id                 1002
name                 Paul Wambui
department                 Sales
city                     Nairobi
salary                  122705.0
years_experience              19
performance_score            4.4
hire_date             2015-01-19
Name: 1, dtype: object

In [71]:
df1.loc[0,'salary']

np.float64(132468.0)

In [73]:
salary_greater_than_133k=df1.query("salary>133000")

In [74]:
salary_greater_than_133k.describe()

       employee_id         salary  years_experience  performance_score
count    37.000000      37.000000         37.000000          32.000000
mean   1098.459459  141098.756757          8.405405           3.218750
std      56.205276    4841.544057          6.134871           1.075066
min    1007.000000  133081.000000          0.000000           1.200000
25%    1049.000000  136476.000000          3.000000           2.600000
50%    1098.000000  141317.000000          8.000000           3.450000
75%    1148.000000  145359.000000         13.000000           4.025000
max    1191.000000  148894.000000         18.000000           4.900000